/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariopila;

/**
 *
 * @author SENA
 */
public class pila extends javax.swing.JFrame {

    /**
     * Se crear el nodo con el contenedor y apuntador
     */
    class Nodo{
        char simbolo;
        Nodo sig;
    }
    
    private Nodo raiz;
    
    pila() {
        initComponents();
        raiz=null;
    }
    
    public void Insertar(char x){
        Nodo nuevo = new Nodo();
        nuevo.simbolo = x;
        if (raiz == null) {
            nuevo.sig = null;
            raiz = nuevo;
        }else{
            nuevo.sig = raiz;
            raiz = nuevo;
        }
    }
    
    public char Extraer (){
        if(raiz!=null){
           char informacion = raiz.simbolo;
           raiz = raiz.sig;
           return informacion;
        }else{
            return Character.MAX_VALUE;
        }
    }
    
    public boolean Vacia(){
        if(raiz == null){
            return true;
        }else{
            return false;
        }
    }
    
    public boolean Balanceada(){
        pila pila1 = new pila();
        String cadena = tf1.getText();
        for(int f = 0 ; f < cadena.length();f++){
            if(cadena.charAt(f) == '(' || cadena.charAt(f) == '[' || cadena.charAt(f) == '{'){
                pila1.Insertar(cadena.charAt(f));
            }else{
                if(cadena.charAt(f)==')'){
                    if(pila1.Extraer() != '('){
                        return false;
                    }
                }else{
                    if(cadena.charAt(f)==']'){
                        if(pila1.Extraer() != '['){
                            return false;
                        }
                    }else{
                        if (cadena.charAt(f) == '}'){
                            if (pila1.Extraer() != '{'){
                                return false;
                            }
                        }
                    }
                }
            }
        }
        if(pila1.Vacia()){
            return true;
        }else{
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1);
        tf1.setBounds(160, 130, 380, 60);

        boton1.setText("Comprobar Formula");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);
        boton1.setBounds(270, 210, 180, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        if (Balanceada()){
            setTitle("Esta correctamente balanceada.");
        }else{
            setTitle("No esta correctamente balanceada.");
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
